--- 
- name: Fase 3 Konfigurasi...
  hosts: all
  gather_facts: no
  tasks:
    - name: 0. Konfigurasi IP
      community.routeros.command:
        commands:
          - /ip address add address={{ new_ip }} interface=ether2